// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/proto.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_1223a48888ada580, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_1223a48888ada580, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StringMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_1223a48888ada580, []int{2}
}
func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (dst *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(dst, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*StringMessage)(nil), "proto.StringMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteGuideClient is the client API for RouteGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteGuideClient interface {
	GetName(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
	GetInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type routeGuideClient struct {
	cc *grpc.ClientConn
}

func NewRouteGuideClient(cc *grpc.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) GetName(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.RouteGuide/GetName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/proto.RouteGuide/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) GetInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.RouteGuide/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RouteGuide service

type RouteGuideServer interface {
	GetName(context.Context, *Request) (*Response, error)
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	GetInfo(context.Context, *Request) (*Response, error)
}

func RegisterRouteGuideServer(s *grpc.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RouteGuide/GetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).GetName(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RouteGuide/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RouteGuide/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).GetInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetName",
			Handler:    _RouteGuide_GetName_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _RouteGuide_Echo_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _RouteGuide_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

func init() { proto.RegisterFile("proto/proto.proto", fileDescriptor_proto_1223a48888ada580) }

var fileDescriptor_proto_1223a48888ada580 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0x51, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x68, 0xad, 0x0e, 0x58, 0x75, 0xa8, 0x50, 0xa3, 0x88, 0x2c, 0x08, 0x22, 0xd2,
	0x45, 0x7d, 0xf3, 0x59, 0x29, 0x3e, 0xa8, 0x10, 0x4f, 0xb0, 0x36, 0xd3, 0x74, 0x21, 0x99, 0x89,
	0xdd, 0x4d, 0xf1, 0xd9, 0x2b, 0x78, 0x32, 0xf1, 0x0a, 0x1e, 0x44, 0xd8, 0x44, 0x21, 0x20, 0xf8,
	0x32, 0xbb, 0x33, 0xff, 0xcf, 0xff, 0xfd, 0xb0, 0x5b, 0x2d, 0xc5, 0x8b, 0x0e, 0x73, 0x12, 0x26,
	0xf6, 0xc3, 0x93, 0x1c, 0xe6, 0x22, 0x79, 0x41, 0xda, 0x54, 0x56, 0x1b, 0x66, 0xf1, 0xc6, 0x5b,
	0x61, 0xd7, 0x98, 0xd4, 0x3e, 0x0c, 0x52, 0x7a, 0xa9, 0xc9, 0x79, 0x1c, 0x42, 0x6c, 0xb3, 0x71,
	0x74, 0x1c, 0x9d, 0x6e, 0xa6, 0xb1, 0xcd, 0xd4, 0x11, 0x6c, 0xa4, 0xe4, 0x2a, 0x61, 0x47, 0x88,
	0xd0, 0x63, 0x53, 0x52, 0xab, 0x86, 0xbf, 0x3a, 0x81, 0xad, 0x27, 0xbf, 0xb4, 0x9c, 0xdf, 0x93,
	0x73, 0x26, 0x27, 0x1c, 0x41, 0x7f, 0x65, 0x8a, 0xfa, 0xc7, 0xd5, 0x2c, 0x97, 0x1f, 0x11, 0x40,
	0x2a, 0xb5, 0xa7, 0x69, 0x6d, 0x33, 0xc2, 0x73, 0x18, 0x4c, 0xc9, 0x3f, 0x98, 0x92, 0x70, 0xd8,
	0x74, 0x98, 0xb4, 0x05, 0x92, 0xed, 0xdf, 0xbd, 0xa1, 0xaa, 0x35, 0x7c, 0x84, 0xde, 0xed, 0x6c,
	0x21, 0x38, 0x6a, 0xa5, 0x0e, 0x30, 0xf9, 0xf3, 0xaa, 0x0e, 0xde, 0x3e, 0xbf, 0xde, 0xe3, 0x3d,
	0xb5, 0xa3, 0x57, 0x17, 0x9a, 0x5e, 0x4d, 0x59, 0x15, 0xa4, 0x69, 0xb6, 0x90, 0xeb, 0xe8, 0x0c,
	0x6f, 0x02, 0xfe, 0x8e, 0xe7, 0xf2, 0x3f, 0x7e, 0x1c, 0x82, 0x10, 0x3b, 0x41, 0x96, 0xe7, 0xf2,
	0xbc, 0x1e, 0x9c, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x60, 0xde, 0x3f, 0x0b, 0x76, 0x01,
	0x00, 0x00,
}
